dependencies:
- name: postgresql
  version: 3.x.x
  repository: http://172.19.3.13:8080/
- name: redis
  version: 6.4.4
  repository: http://172.19.3.13:8080/
  condition: redis.enabled
- name: memcached
  version: 2.7.1
  repository: http://172.19.3.13:8080/
  condition: memcached.enabled
