apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "weblate.fullname" . }}
  labels:
    app: {{ template "weblate.name" . }}
    chart: {{ template "weblate.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app: {{ template "weblate.name" . }}
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: {{ template "weblate.name" . }}
        chart: {{ template "weblate.chart" . }}
        release: {{ .Release.Name | quote }}
    spec:
{{- include "weblate.imagePullSecrets" . | indent 6 }}
      containers:
      - name: {{ template "weblate.fullname" . }}
        image: {{ template "weblate.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: REDIS_HOST
          value: {{ template "weblate.redis.host" . }}
        - name: REDIS_PORT
          value: {{ template "weblate.redis.port" . }}
        - name: POSTGRES_HOST
          value: {{ template "weblate.postgresql.fullname" . }}
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DATABASE
          value: {{ .Values.postgresql.postgresqlDatabase | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.postgresqlUsername | quote }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "weblate.postgresql.fullname" . }}
              key: postgresql-password
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "weblate.postgresql.fullname" . }}
              key: postgresql-password
        - name: WEBLATE_SITE_TITLE
          value: {{ .Values.weblateSiteTitle | quote }}
        - name: WEBLATE_ADMIN_NAME
          value: {{ .Values.weblateAdminName | quote }}
        - name: WEBLATE_ADMIN_EMAIL
          value: {{ .Values.weblateAdminEmail | quote }}
        - name: WEBLATE_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "weblate.fullname" . }}
              key: weblate-password
        - name: WEBLATE_REGISTRATION_OPEN
          value: {{ .Values.weblateRegistrationOpen | quote }}
        {{- if .Values.allowedHosts }}
        - name: WEBLATE_ALLOWED_HOSTS
          value: {{ .Values.allowedHosts | quote }}
        {{- end }}
        {{- if .Values.smtpHost }}
        - name: WEBLATE_EMAIL_HOST
          value: {{ .Values.smtpHost | quote }}
        {{- end }}
        {{- if .Values.smtpPort }}
        - name: WEBLATE_EMAIL_PORT
          value: {{ .Values.smtpPort | quote }}
        {{- end }}
        {{- if .Values.smtpProtocol }}
        - name: SMTP_PROTOCOL
          value: {{ .Values.smtpProtocol | quote }}
        {{- end }}
        {{- if .Values.smtpUser }}
        - name: WEBLATE_EMAIL_HOST_USER
          value: {{ .Values.smtpUser | quote }}
        {{- end }}
        {{- if .Values.smtpPassword }}
        - name: WEBLATE_EMAIL_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "weblate.fullname" . }}
              key: smtp-password
        {{- end }}
        {{- if .Values.serverEmail }}
        - name: WEBLATE_SERVER_EMAIL
          value: {{ .Values.serverEmail | quote }}
        {{- end }}
        {{- if .Values.defaultFromEmail }}
        - name: WEBLATE_DEFAULT_FROM_EMAIL
          value: {{ .Values.serverEmail | quote }}
        {{- end }}
        ports:
        - name: http
          containerPort: 8069
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: weblate-data
          mountPath: /bitnami/weblate
      volumes:
      - name: weblate-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "weblate.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end }}
