apiVersion: v1
kind: Secret
metadata:
  name: {{ template "weblate.fullname" . }}
  labels:
    app: {{ template "weblate.name" . }}
    chart: {{ template "weblate.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{ if .Values.weblatePassword }}
  weblate-password: {{ .Values.weblatePassword | b64enc | quote }}
  {{ else }}
  weblate-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.smtpPassword }}
  smtp-password: {{ .Values.smtpPassword | b64enc | quote }}
  {{ end }}
  {{ if .Values.postgresql.postgresqlPassword }}
  postgresql-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  {{ else }}
  postgresql-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
