{{- if .Values.persistence.pv.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.volumeName | quote }}
  labels:
    app: {{  template "odoo.name"  . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    chart: {{ template "odoo.chart" . }}
spec:
  storageClassName: {{ .Values.persistence.pv.storageClassName | qoute }}
  capacity:
    storage: {{ .Values.persistence.pv.capacity.storage | quote }}
  accessMode:
    - {{ .Values.persistence.pv.accessMode | quote }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.pv.persistentVolumeReclaimPolicy | quote }}  
{{- end }}
