apiVersion: v1
name: odoo-clone-1
version: 12.0.3
appVersion: 12.0.20190410
description: A suite of web based open source business apps.
home: https://www.odoo.com/
icon: https://bitnami.com/assets/stacks/odoo/img/odoo-stack-110x117.png
keywords:
- odoo
- crm
- www
- http
- web
sources:
- https://github.com/bitnami/bitnami-docker-odoo
maintainers:
- name: Bitnami
  email: containers@bitnami.com
engine: gotpl
